name: EPG update

on:
  schedule:
    - cron: '0 */4 * * *' # Daily schedule
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

   

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
           node-version: 18
      
    - name: npm grab epg
      run: |
          npm install
          npm run grab -- --channels=path/to/pl.channels.xml --maxConnections=10 --output=guide.xml


          
    - name: Commit changes
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "Your Name"
        git add -f guide.xml
        git commit -m "Update xml"
        git push
