name: Auto Update EPG
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Jakarta"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: install dependencies
        run: npm install
      - name: check *.channels.xml
        run: |
          npm run channels:lint
      - name: guide
        run: |
          for i in {1..3}; do
            npm run grab -- --channels=plchannels.xml --output=guide.xml --maxConnections=5 
          done
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.guide.xml"
          allowUpdates: true
          generateReleaseNotes: false
          replacesArtifacts: true
          removeArtifacts: true
          prerelease: false
          draft: false
          makeLatest: true
          tag: 1.0.0


          
